import InputError from '@/components/input-error';
import PanelLayout from '@/components/panel-layout';
import RichTextEditor from '@/components/rich-text-editor';
import { Head, Link, useForm } from '@inertiajs/react';
import { ArrowLeft, Save } from 'lucide-react';
import { FormEvent } from 'react';

type Field = { name: string; label: string; type?: 'text'|'email'|'password'|'number'|'textarea'|'checkbox'|'datetime-local'|'file' };
type Value = string|number|boolean|File|null;
type Props = { resource:string;title:string;fields:Field[];record:Record<string,Value>|null };

function initialValue(field:Field,record:Props['record']):Value{if(field.type==='password'||field.type==='file')return field.type==='file'?null:'';if(field.type==='checkbox')return Boolean(record?.[field.name]);const value=record?.[field.name];if(field.type==='datetime-local'&&value)return String(value).replace(' ','T').slice(0,16);return value??''}

export default function ResourceForm({resource,title,fields,record}:Props){
    const editing=Boolean(record);
    const {data,setData,post,processing,errors}=useForm<Record<string,Value>>(Object.fromEntries(fields.map(field=>[field.name,initialValue(field,record)])));
    const submit=(event:FormEvent)=>{event.preventDefault();post(editing?`/admin/${resource}/${record?.id}`:`/admin/${resource}`,editing?{forceFormData:true}:undefined)};
    return <PanelLayout area="admin" title={editing?`Editar ${title.toLowerCase()}`:`Novo em ${title.toLowerCase()}`} description={editing?`Alterando o registro #${record?.id}`:'Preencha os dados abaixo para cadastrar um novo registro.'}>
        <Head title={`${editing?'Editar':'Novo'} | ${title}`}/><form onSubmit={submit} className="border border-black/10 bg-white"><div className="grid gap-6 p-6 sm:grid-cols-2 lg:p-8">{fields.map(field=>{const error=errors[field.name];if(field.type==='checkbox')return <label key={field.name} className="flex min-h-14 cursor-pointer items-center gap-3 border border-black/10 bg-[#f4f4f2] px-4"><input type="checkbox" checked={Boolean(data[field.name])} onChange={event=>setData(field.name,event.target.checked)} className="h-5 w-5 accent-[#d60057]"/><span className="text-sm font-bold">{field.label}</span><InputError message={error}/></label>;if(field.name==='content')return <label key={field.name} className="sm:col-span-2"><span className="mb-2 block text-sm font-bold">{field.label}</span><RichTextEditor value={String(data[field.name]??'')} onChange={value=>setData(field.name,value)}/><InputError message={error}/></label>;if(field.type==='file')return <label key={field.name} className="sm:col-span-2"><span className="mb-2 block text-sm font-bold">{field.label}</span>{editing&&record?.[field.name]&&<img src={`/storage/${record[field.name]}`} alt="Imagem atual" className="mb-4 h-28 w-44 border border-black/10 bg-white object-contain p-2"/>}<input type="file" accept="image/*" onChange={event=>setData(field.name,event.target.files?.[0]??null)} className="w-full border border-dashed border-black/20 bg-[#f4f4f2] p-5 text-sm file:mr-4 file:border-0 file:bg-black file:px-4 file:py-2 file:font-bold file:text-white"/><InputError message={error}/></label>;const wide=field.type==='textarea';return <label key={field.name} className={wide?'sm:col-span-2':''}><span className="mb-2 block text-sm font-bold">{field.label}</span>{wide?<textarea value={String(data[field.name]??'')} onChange={event=>setData(field.name,event.target.value)} className="min-h-32 w-full border border-black/15 bg-[#f4f4f2] p-4 outline-none focus:border-[#d60057]"/>:<input type={field.type??'text'} step={field.type==='number'?'0.01':undefined} value={String(data[field.name]??'')} onChange={event=>setData(field.name,event.target.value)} disabled={editing&&resource==='ordens'&&field.name==='id'} className="h-12 w-full border border-black/15 bg-[#f4f4f2] px-4 outline-none focus:border-[#d60057] disabled:opacity-50"/>}<InputError message={error}/></label>})}</div><div className="flex flex-col-reverse justify-between gap-3 border-t border-black/10 bg-black/[.02] p-5 sm:flex-row"><Link href={`/admin/${resource}`} className="flex items-center justify-center gap-2 border border-black/15 px-5 py-3 text-sm font-bold"><ArrowLeft size={17}/> Cancelar</Link><button disabled={processing} className="flex items-center justify-center gap-2 bg-[#d60057] px-6 py-3 text-sm font-bold text-white disabled:opacity-50"><Save size={17}/>{processing?'Salvando...':'Salvar registro'}</button></div></form>
    </PanelLayout>;
}
